# Porta do servidor REST (Cliente)
server.port=8080

# Porta do servidor gRPC
grpc.server.port=9090

# Configurando o cliente gRPC para apontar para o servidor local
grpc.client.clima-server.address=static://localhost:9090
grpc.client.clima-server.negotiation-type=plaintext